# Generated by Django 4.2.5 on 2023-10-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
